language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
env:
  - LEMUR_CONFIG=$(PWD)/config_travis.cfg # needs to be set to an absolute path
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nose2
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
